-- Insert SQLs for Current PersIDNum --

Insert into AgentStatusHistory values (243251,User,getdate(),'N','T')
Insert into AgentStatusHistory values (293872,User,getdate(),'N','T')
Insert into AgentStatusHistory values (475883,User,getdate(),'N','T')
Insert into AgentStatusHistory values (475896,User,getdate(),'N','T')
Insert into AgentStatusHistory values (475969,User,getdate(),'N','T')
Insert into AgentStatusHistory values (480065,User,getdate(),'N','T')
Insert into AgentStatusHistory values (480066,User,getdate(),'N','T')
Insert into AgentStatusHistory values (480097,User,getdate(),'N','T')
Insert into AgentStatusHistory values (480157,User,getdate(),'N','T')
Insert into AgentStatusHistory values (481890,User,getdate(),'N','T')
Insert into AgentStatusHistory values (483977,User,getdate(),'N','T')
Insert into AgentStatusHistory values (483989,User,getdate(),'N','T')
Insert into AgentStatusHistory values (484005,User,getdate(),'N','T')
Insert into AgentStatusHistory values (490935,User,getdate(),'N','T')
Insert into AgentStatusHistory values (490944,User,getdate(),'N','T')
Insert into AgentStatusHistory values (490977,User,getdate(),'N','T')
Insert into AgentStatusHistory values (490981,User,getdate(),'N','T')
Insert into AgentStatusHistory values (491014,User,getdate(),'N','T')
Insert into AgentStatusHistory values (501978,User,getdate(),'N','T')
Insert into AgentStatusHistory values (502045,User,getdate(),'N','T')

Insert into AgentStatusHistory values (502530,User,getdate(),'N','T')
Insert into AgentStatusHistory values (504155,User,getdate(),'N','T')
Insert into AgentStatusHistory values (504178,User,getdate(),'N','T')
Insert into AgentStatusHistory values (504189,User,getdate(),'N','T')
Insert into AgentStatusHistory values (515616,User,getdate(),'N','T')
Insert into AgentStatusHistory values (515633,User,getdate(),'N','T')
Insert into AgentStatusHistory values (515667,User,getdate(),'N','T')
Insert into AgentStatusHistory values (515668,User,getdate(),'N','T')
Insert into AgentStatusHistory values (520242,User,getdate(),'N','T')
Insert into AgentStatusHistory values (521167,User,getdate(),'N','T')
Insert into AgentStatusHistory values (521961,User,getdate(),'N','T')
Insert into AgentStatusHistory values (521971,User,getdate(),'N','T')
Insert into AgentStatusHistory values (522689,User,getdate(),'N','T')
Insert into AgentStatusHistory values (522895,User,getdate(),'N','T')
Insert into AgentStatusHistory values (523945,User,getdate(),'N','T')
Insert into AgentStatusHistory values (524120,User,getdate(),'N','T')
Insert into AgentStatusHistory values (527221,User,getdate(),'N','T')
Insert into AgentStatusHistory values (527300,User,getdate(),'N','T')
Insert into AgentStatusHistory values (527356,User,getdate(),'N','T')
Insert into AgentStatusHistory values (527433,User,getdate(),'N','T')


-- Insert SQLs for New PersIDNum --

Insert into AgentStatusHistory values (915126,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (771403,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875613,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875601,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (874756,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875556,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875557,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (876287,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (876150,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875834,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (876068,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (874889,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (876058,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875230,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875213,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (876171,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875185,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875245,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875904,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875917,User,getdate(),'Y','T')

Insert into AgentStatusHistory values (875388,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875062,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875024,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875058,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875713,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875739,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (876361,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (875762,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (797380,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (771643,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (804604,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (792169,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (793909,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (793827,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (791729,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (790298,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (802394,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (802607,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (802624,User,getdate(),'Y','T')
Insert into AgentStatusHistory values (786550,User,getdate(),'Y','T')
